version: '3.8'

services:
  tencyclesoffate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tencyclesoffate
    restart: unless-stopped
    
    # 端口映射
    ports:
      - "8000:8000"
    
    # 数据卷挂载（持久化数据和配置文件）
    volumes:
      - ./data:/app/data
      - ./backend/.env:/app/backend/.env:ro
    
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 网络配置
    networks:
      - tencyclesoffate-network

networks:
  tencyclesoffate-network:
    driver: bridge
