version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tencyclesoffate-mysql
    restart: unless-stopped
    # 环境变量
    environment:
      MYSQL_ROOT_PASSWORD: reset-your-mysql-password
      MYSQL_DATABASE: tencyclesoffate
      MYSQL_USER: tencyclesoffate
      MYSQL_PASSWORD: reset-your-mysql-password
    # 数据卷挂载（持久化数据库数据）
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - tencyclesoffate-network

  tencyclesoffate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tencyclesoffate
    restart: unless-stopped
    # 依赖关系
    depends_on:
      mysql:
        condition: service_healthy
    # 端口映射
    ports:
      - "8000:8000"
    # 数据卷挂载（持久化数据和配置文件）
    volumes:
      - ./data:/app/data
      - ./backend/.env:/app/backend/.env:ro
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # 网络配置
    networks:
      - tencyclesoffate-network

volumes:
  mysql-data:
    driver: local

networks:
  tencyclesoffate-network:
    driver: bridge
