version: '3.8'

services:
  ten-cycles-of-fate:
    # image: gabrlie/ten-cycles-of-fate:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ten-cycles-of-fate
    restart: unless-stopped
    # 环境变量配置
    environment:
      # OpenAI API 设置
      OPENAI_API_KEY: ${OPENAI_API_KEY:-your_openai_api_key_here}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:-https://api.openai.com/v1}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o}
      OPENAI_MODEL_CHEAT_CHECK: ${OPENAI_MODEL_CHEAT_CHECK:-gpt-3.5-turbo}
      # JWT 设置
      SECRET_KEY: ${SECRET_KEY:-please_change_this_secret_key_in_production}
      ALGORITHM: ${ALGORITHM:-HS256}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-600}
      # Linux.do OAuth 设置
      LINUXDO_CLIENT_ID: ${LINUXDO_CLIENT_ID:-}
      LINUXDO_CLIENT_SECRET: ${LINUXDO_CLIENT_SECRET:-}
      LINUXDO_SCOPE: ${LINUXDO_SCOPE:-read}
      ENABLE_LINUXDO_OAUTH: ${ENABLE_LINUXDO_OAUTH:-true}
      ENABLE_LOCAL_LOGIN: ${ENABLE_LOCAL_LOGIN:-true}
      ENABLE_LOCAL_REGISTRATION: ${ENABLE_LOCAL_REGISTRATION:-true}
      # 数据库设置
      DATABASE_URL: ${DATABASE_URL:-sqlite:///data/tencyclesoffate.db}
      # 服务器设置
      HOST: ${HOST:-0.0.0.0}
      PORT: ${PORT:-8000}
      UVICORN_RELOAD: ${UVICORN_RELOAD:-false}
    # 端口映射
    ports:
      - "${EXTERNAL_PORT:-8000}:8000"
    # 数据卷挂载
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # 网络配置
    networks:
      - ten-cycles-of-fate-network

networks:
  ten-cycles-of-fate-network:
    driver: bridge
